---
- name: Manage Azure Service Bus Topics and Queues
  hosts: localhost
  gather_facts: no
  collections:
  - azure.azcollection
  tasks:
  - name: Create a Service Bus Topic
    azure_rm_servicebustopic:
      resource_group: "your-resource-group"
      namespace: "your-service-bus-namespace"
      name: "your-topic-name"
      default_message_time_to_live_seconds: "P60D"
      state: "present"
